from django.urls import path

from . import views

urlpatterns = [
    path("", views.home),
    #cimri urls;
    path("cimriHome", views.cimriHome),
    path("filteredToHP", views.filteredToHP),
    path("filteredToCasper", views.filteredToCasper),
    path("filteredToLenovo", views.filteredToLenovo),
    path("filteredToDell", views.filteredToDell),
    path("filteredToMonster", views.filteredToMonster),
    path("filteredToHuawei", views.filteredToHuawei),
    path("filteredToApple", views.filteredToApple),
    path("filteredToHonor", views.filteredToHonor),
    path("filteredToDynabook", views.filteredToDynabook),
    path("ucuzdanPahaliya", views.ucuzdanPahaliya),
    path("pahalidanUcuza", views.pahalidanUcuza),
    path("yuksekPuandanDusukPuana", views.yuksekPuandanDusukPuana),
    path("dusukPuandanYuksekPuana", views.dusukPuandanYuksekPuana),
    path("filteredToAMDRyzen5", views.filteredToAMDRyzen5),
    path("filteredToAMDRyzen7", views.filteredToAMDRyzen7),
    path("filteredToIntelCoreI5", views.filteredToIntelCoreI5),
    path("filteredToIntelCoreI7", views.filteredToIntelCoreI7),
    path("filteredToAppleM1", views.filteredToAppleM1),
    path("filteredToIntelCoreI9", views.filteredToIntelCoreI9),
    path("filteredTo8GBRAM", views.filteredTo8GBRAM),
    path("filteredTo16GBRAM", views.filteredTo16GBRAM),
    path("filteredTo32GBRAM", views.filteredTo32GBRAM),
    path("filteredToDahiliEkranKarti", views.filteredToDahiliEkranKarti),
    path("filteredToIntelIrisGraphics", views.filteredToIntelIrisGraphics),
    path("filteredToNvidiaGeForceRTX3060", views.filteredToNvidiaGeForceRTX3060),
    path("filteredToM1Pro14Cekirdekli", views.filteredToM1Pro14Cekirdekli),
    path("filteredToM28Cekirdekli", views.filteredToM28Cekirdekli),
    path("filteredToAMDRadeonGraphics", views.filteredToAMDRadeonGraphics),
    path("filteredToNvidiaGeForceMX450", views.filteredToNvidiaGeForceMX450),
    path("filteredToNvidiaGeForceRTX3080", views.filteredToNvidiaGeForceRTX3080),
    path("filteredToIntelUHDGraphics620", views.filteredToIntelUHDGraphics620),

    #trendyol urls;
    path("trendyolHome", views.trendyolHome),
    path("filteredToHPTRENDYOL", views.filteredToHPTRENDYOL),
    path("filteredToCasperTRENDYOL", views.filteredToCasperTRENDYOL),
    path("filteredToLenovoTRENDYOL", views.filteredToLenovoTRENDYOL),
    path("filteredToDellTRENDYOL", views.filteredToDellTRENDYOL),
    path("filteredToMonsterTRENDYOL", views.filteredToMonsterTRENDYOL),
    path("filteredToHuaweiTRENDYOL", views.filteredToHuaweiTRENDYOL),
    path("filteredToAppleTRENDYOL", views.filteredToAppleTRENDYOL),
    path("filteredToHonorTRENDYOL", views.filteredToHonorTRENDYOL),
    path("filteredToDynabookTRENDYOL", views.filteredToDynabookTRENDYOL),
    path("ucuzdanPahaliyaTRENDYOL", views.ucuzdanPahaliyaTRENDYOL),
    path("pahalidanUcuzaTRENDYOL", views.pahalidanUcuzaTRENDYOL),
    path("yuksekPuandanDusukPuanaTRENDYOL", views.yuksekPuandanDusukPuanaTRENDYOL),
    path("dusukPuandanYuksekPuanaTRENDYOL", views.dusukPuandanYuksekPuanaTRENDYOL),
    path("filteredToAMDRyzen5TRENDYOL", views.filteredToAMDRyzen5TRENDYOL),
    path("filteredToAMDRyzen7TRENDYOL", views.filteredToAMDRyzen7TRENDYOL),
    path("filteredToIntelCoreI5TRENDYOL", views.filteredToIntelCoreI5TRENDYOL),
    path("filteredToIntelCoreI7TRENDYOL", views.filteredToIntelCoreI7TRENDYOL),
    path("filteredToAppleM1TRENDYOL", views.filteredToAppleM1TRENDYOL),
    path("filteredToIntelCoreI9TRENDYOL", views.filteredToIntelCoreI9TRENDYOL),
    path("filteredTo8GBRAMTRENDYOL", views.filteredTo8GBRAMTRENDYOL),
    path("filteredTo16GBRAMTRENDYOL", views.filteredTo16GBRAMTRENDYOL),
    path("filteredTo32GBRAMTRENDYOL", views.filteredTo32GBRAMTRENDYOL),
    path("filteredToDahiliEkranKartiTRENDYOL", views.filteredToDahiliEkranKartiTRENDYOL),
    path("filteredToIntelIrisGraphicsTRENDYOL", views.filteredToIntelIrisGraphicsTRENDYOL),
    path("filteredToNvidiaGeForceRTX3060TRENDYOL", views.filteredToNvidiaGeForceRTX3060TRENDYOL),
    path("filteredToM1Pro14CekirdekliTRENDYOL", views.filteredToM1Pro14CekirdekliTRENDYOL),
    path("filteredToM28CekirdekliTRENDYOL", views.filteredToM28CekirdekliTRENDYOL),
    path("filteredToAMDRadeonGraphicsTRENDYOL", views.filteredToAMDRadeonGraphicsTRENDYOL),
    path("filteredToNvidiaGeForceMX450TRENDYOL", views.filteredToNvidiaGeForceMX450TRENDYOL),
    path("filteredToNvidiaGeForceRTX3080TRENDYOL", views.filteredToNvidiaGeForceRTX3080TRENDYOL),
    path("filteredToIntelUHDGraphics620TRENDYOL", views.filteredToIntelUHDGraphics620TRENDYOL),

    #urun ozellikleri url;
    path("cimriUrunOzelligi/<str:id>", views.cimriUrunOzelligi),
    path("trendyolUrunOzelligi/<str:id>", views.trendyolUrunOzelligi)
]